package baseLanguage.sugar.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"baseLanguage.sugar.structure.IfInlineStatement", "baseLanguage.sugar.structure.StringFormat", "baseLanguage.sugar.structure.UnlessInlineStatement"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 1:
        return new StringFormat_BehaviorDescriptor();
      case 2:
        return new UnlessInlineStatement_BehaviorDescriptor();
      case 0:
        return new IfInlineStatement_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
