package baseLanguage.sugar.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public abstract class ConditionalInlineStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public ConditionalInlineStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "baseLanguage.sugar.structure.ConditionalInlineStatement";
  }
}
