package baseLanguage.sugar.behavior;

/*Generated by MPS */


public class IfInlineStatement_BehaviorDescriptor extends ConditionalInlineStatement_BehaviorDescriptor {
  public IfInlineStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "baseLanguage.sugar.structure.IfInlineStatement";
  }
}
