package baseLanguage.sugar.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class StringFormat_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public StringFormat_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "baseLanguage.sugar.structure.StringFormat";
  }
}
