package baseLanguage.sugar.behavior;

/*Generated by MPS */


public class UnlessInlineStatement_BehaviorDescriptor extends ConditionalInlineStatement_BehaviorDescriptor {
  public UnlessInlineStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "baseLanguage.sugar.structure.UnlessInlineStatement";
  }
}
