package baseLanguage.sugar.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilders;
import jetbrains.mps.lang.dataFlow.DataFlowManager;

public class DFABuilders extends DataFlowBuilders {
  public void install(DataFlowManager manager) {
    manager.register("baseLanguage.sugar.structure.ConditionalInlineStatement", new ConditionalInlineStatement_DataFlow());
    manager.register("baseLanguage.sugar.structure.StringFormat", new StringFormat_DataFlow());
  }
}
