package baseLanguage.sugar.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IfInlineStatement extends ConditionalInlineStatement {
  public static final String concept = "baseLanguage.sugar.structure.IfInlineStatement";

  public IfInlineStatement(SNode node) {
    super(node);
  }

  public static IfInlineStatement newInstance(SModel sm, boolean init) {
    return (IfInlineStatement) SModelUtil_new.instantiateConceptDeclaration("baseLanguage.sugar.structure.IfInlineStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IfInlineStatement newInstance(SModel sm) {
    return IfInlineStatement.newInstance(sm, false);
  }
}
