package baseLanguage.sugar.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"baseLanguage.sugar.structure.ConditionalInlineStatement", "baseLanguage.sugar.structure.IfInlineStatement", "baseLanguage.sugar.structure.StringFormat", "baseLanguage.sugar.structure.UnlessInlineStatement"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("baseLanguage.sugar.structure.ConditionalInlineStatement", "jetbrains.mps.baseLanguage.structure.Statement", false, new String[]{"jetbrains.mps.baseLanguage.structure.Statement"}, new String[]{}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("baseLanguage.sugar.structure.IfInlineStatement", "baseLanguage.sugar.structure.ConditionalInlineStatement", false, new String[]{"baseLanguage.sugar.structure.ConditionalInlineStatement"}, new String[]{}, new String[]{});
      case 2:
        return new CompiledConceptDescriptor("baseLanguage.sugar.structure.StringFormat", "jetbrains.mps.baseLanguage.structure.Expression", false, new String[]{"jetbrains.mps.baseLanguage.structure.Expression"}, new String[]{}, new String[]{});
      case 3:
        return new CompiledConceptDescriptor("baseLanguage.sugar.structure.UnlessInlineStatement", "baseLanguage.sugar.structure.ConditionalInlineStatement", false, new String[]{"baseLanguage.sugar.structure.ConditionalInlineStatement"}, new String[]{}, new String[]{});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
