package baseLanguage.sugar.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Sugar_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("d965f506-a0c0-43c2-871a-b97ce8f6c751(baseLanguage.sugar)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
