package baseLanguage.sugar.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class UnlessInlineStatement extends ConditionalInlineStatement {
  public static final String concept = "baseLanguage.sugar.structure.UnlessInlineStatement";

  public UnlessInlineStatement(SNode node) {
    super(node);
  }

  public static UnlessInlineStatement newInstance(SModel sm, boolean init) {
    return (UnlessInlineStatement) SModelUtil_new.instantiateConceptDeclaration("baseLanguage.sugar.structure.UnlessInlineStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static UnlessInlineStatement newInstance(SModel sm) {
    return UnlessInlineStatement.newInstance(sm, false);
  }
}
