package baseLanguage.sugar.test;

/*Generated by MPS */

import junit.framework.TestCase;
import junit.framework.Assert;

public class IfTest_Test extends TestCase {
  public void test_triggered() throws Exception {
    int t = 0;
    if (t > 0) {
      t = 5;
    }
    Assert.assertSame(t, 0);
  }

  public void test_notTriggered() throws Exception {
    int t = 0;
    if (t == 0) {
      t = 5;
    }
    Assert.assertSame(t, 5);
  }
}
