package baseLanguage.sugar.test;

/*Generated by MPS */

import junit.framework.TestCase;
import junit.framework.Assert;
import java.util.Formatter;

public class StringFormatTest_Test extends TestCase {
  public void test_format() throws Exception {
    Assert.assertEquals(new Formatter().format("My name is %s, I am %d years old", "Isaac Newton", 18).toString(), "My name is Isaac Newton, I am 18 years old");
  }

  public void test_noParams() throws Exception {
    Assert.assertEquals(new Formatter().format("One and only", 1, "only").toString(), "One and only");
  }

  public StringFormatTest_Test() {
  }
}
