package baseLanguage.sugar.test;

/*Generated by MPS */

import junit.framework.TestCase;
import junit.framework.Assert;

public class UnlessTest_Test extends TestCase {
  public void test_unlessTriggered() throws Exception {
    int t = 0;
    if (!(t == 0)) {
      t = 5;
    }
    Assert.assertSame(t, 0);
  }

  public void test_notTriggered() throws Exception {
    int t = 0;
    if (!(false)) {
      t = 5;
    }
    Assert.assertSame(t, 5);
  }

  public UnlessTest_Test() {
  }
}
